routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return redirect('/login');
});

Route::get('/', 'UserController@landing');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('infopages', 'InfoPagesController');

Route::resource('magazine', 'MagazineController');

Route::resource('notices', 'NoticeController');

Route::post('magazine/image', 'MagazineController@image')->name('magazine.image');

Route::resource('pages', 'PageController');

Route::get('/magazinePage/{id}','MagazineController@pages');

Route::resource('subscription', 'SubscriptionController');

Route::post('/contentImage', 'MagazineController@contentImage');

Route::post('/contentGallery/{id}', 'MagazineController@contentGallery');

Route::post('/pagePost', 'PageController@pagePost');

Route::get('/goFlow', 'SaleController@goFlow');

Route::post('/flowConfirm', 'SaleController@flowConfirm');

Route::post('/flowResult', 'SaleController@flowResult');

Route::get('/appRegister', 'UserController@appRegister');

Route::get('/paypalReturn', 'SaleController@paypalReturn');

Route::get('/paypalCancel', 'SaleController@paypalCancel');

Route::post('/registerApp', 'UserController@registerApp');

Route::get('/userSuccess', 'UserController@userSuccess');

Route::get('/logout', 'UserController@logout');

Route::delete('/galleryDelete/{id}', 'PageController@galleryDelete');

Route::get('/resetPass', 'UserController@resetPass');

app/Subscription.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Subscription extends Model
{
    protected $fillable = [
        'name', 'price', 'months', 'dollar_price'
    ];

    public function user(){
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/SubscriptionController.php
<?php

namespace App\Http\Controllers;

use App\Subscription;
use Illuminate\Http\Request;
use App\Http\Requests\StoreSubscriptionPost;

class SubscriptionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subs = Subscription::get();

        return view('subscriptions.list', ['subs' => $subs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subscriptions.create', ['sub'=> new Subscription()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSubscriptionPost $request)
    {
        Subscription::create($request->all());

        return back()->with('status', 'Suscripcion Creado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Subscription $subscription)
    {
        return view('subscriptions.edit', ['subscription' => $subscription]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreSubscriptionPost $request, Subscription $subscription)
    {
        $subscription->update($request->validated()); 

        return back()->with('status', 'Suscripcion Actualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subscription $subscription)
    {
        $subscription->delete();

        return back()->with('status', 'Suscripcion Eliminada');
    }

    public function changeSub($id)
    {
        $user = Auth::user();
        $user->subscription_id = $id;
        if($user->update()){
            return 1;
        }

    }

    public function subscriptionselect()
    {
        $subs = Subscription::all();
        $data = "";
        foreach ($subs as $v) {
            $data .= sprintf(
                '<option value="%s">%s %s / %s</option>',
                $v->id,
                $v->name,
                $v->description,
                $v->price
            );
        }
        return $data;
    }
}

resources/views/subscriptions/create.blade.php
@extends('layouts.app')

@section('content')

@if ($errors->any())
@foreach ($errors->all() as $error)
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{$error}}
    </div> 
@endforeach

@endif

    <form action="{{ route('subscription.store')}}" method="POST">

        @csrf
        <input type="hidden" id="token" value="{{csrf_token()}}">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        
        <div class="row clearfix">
            <div class=" col-md-offset-1 col-lg-offset-1 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Crear Subscripcion
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="">Nombre Suscripcion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">title</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Nombre Suscripcion">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Meses Suscripcion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">calendar_today</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="number" name="months" class="form-control" placeholder="Meses Suscripcion">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Precio CLP</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">shop_two</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="number" name="price" id="price" class="form-control" placeholder="CLP">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Precio Dolar</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">shop_two</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="number" name="dollar_price" class="form-control" placeholder="Dolar">
                                    </div>
                                </div>
                            </div>
                            <div class=" row col-md-12 text-right">
                                <input type="submit" value="Crear" class="btn btn-danger" style="width:200px">
                            </div> 
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/subscriptions/edit.blade.php
@extends('layouts.app')

@section('content')

@if ($errors->any())
@foreach ($errors->all() as $error)
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{$error}}
    </div> 
@endforeach

@endif

    <form action="{{ route('subscription.update', $subscription->id)}}" method="POST">
        
        @method('PUT')
        
        @csrf
        <input type="hidden" id="token" value="{{csrf_token()}}">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        
        <div class="row clearfix">
            <div class=" col-md-offset-1 col-lg-offset-1 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Actualizar Subscripcion
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="">Nombre Suscripcion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">title</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" value="{{$subscription->name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Meses Suscripcion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">calendar_today</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="number" name="months" class="form-control" placeholder="Meses Suscripcion" value="{{$subscription->months}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Precio CLP</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">shop_two</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="number" name="price" id="price" class="form-control" value="{{$subscription->price}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Precio Dolar</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">shop_two</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="number" name="dollar_price" class="form-control" placeholder="Dolar" value="{{$subscription->dollar_price}}">
                                    </div>
                                </div>
                            </div>
                            <div class=" row col-md-12 text-right">
                                <input type="submit" value="Actualizar" class="btn btn-danger" style="width:200px">
                            </div>   
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/subscriptions/list.blade.php
@extends('layouts.app')

@section('css')
     <!-- JQuery DataTable Css -->
     <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@endsection

@section('content')

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Suscripciones
                    <form action="{{ route('subscription.create')}}" method="GET" class="pull-right">
                        <button type="sumbit" class="btn btn-primary">Crear Subscripcion</button>
                    </form>
                </h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            <tr>
                                
                                <th>Nombre</th>
                                <th>Meses</th>
                                <th>Precio CLP</th>
                                <th>Precio Dolar</th>
                                <th>Acciones</th>    
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($subs as $s)
                            <tr>
                                <td>{{$s->name}}</td>
                                <td>{{$s->months}}</td>
                                <td>${{$s->price}}</td>
                                <td>${{$s->dollar_price}}</td>
                                <th>
                                    <a href=" {{ route('subscription.edit', $s->id) }} " class="btn btn-primary"> Actualizar </a>
                                    <button data-toggle="modal" data-target="#deleteModal" data-id="{{$s->id}}" class="btn btn-danger"> Eliminar </button>
                                </th>
                            </tr>
                        @endforeach    
                        </tbody>
                    </table>

                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="smallModalLabel">Seguro?</h4>
                                </div>
                                <div class="modal-body">
                                    Seguro?
                                </div>
                                <div class="modal-footer">
                                    <form id="formDelete" method="POST" action="{{ route('subscription.destroy', 0)}}" data-action="{{ route('subscription.destroy', 0)}}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="sumbit" class="btn btn-link waves-effect">Borrar</button>
                                    </form>
                                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
      <!-- Jquery DataTable Plugin Js -->
      <script src="/plugins/jquery-datatable/jquery.dataTables.js"></script>
      <script src="/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
  
      <!-- Custom Js -->

      <script src="/js/pages/tables/jquery-datatable.js"></script>
    <script>
        window.onload = function(){
            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var id = button.data('id') 
    
                action = $('#formDelete').attr('data-action').slice(0,-1) 
                $('#formDelete').attr('action',action + id)
    
                var modal = $(this)
                modal.find('.modal-title').text('Vas a borrar esta suscripcion: ' + id)
                });
        };
    </script>
@endsection