routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return redirect('/login');
});

Route::get('/', 'UserController@landing');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('infopages', 'InfoPagesController');

Route::resource('magazine', 'MagazineController');

Route::resource('notices', 'NoticeController');

Route::post('magazine/image', 'MagazineController@image')->name('magazine.image');

Route::resource('pages', 'PageController');

Route::get('/magazinePage/{id}','MagazineController@pages');

Route::resource('subscription', 'SubscriptionController');

Route::post('/contentImage', 'MagazineController@contentImage');

Route::post('/contentGallery/{id}', 'MagazineController@contentGallery');

Route::post('/pagePost', 'PageController@pagePost');

Route::get('/goFlow', 'SaleController@goFlow');

Route::post('/flowConfirm', 'SaleController@flowConfirm');

Route::post('/flowResult', 'SaleController@flowResult');

Route::get('/appRegister', 'UserController@appRegister');

Route::get('/paypalReturn', 'SaleController@paypalReturn');

Route::get('/paypalCancel', 'SaleController@paypalCancel');

Route::post('/registerApp', 'UserController@registerApp');

Route::get('/userSuccess', 'UserController@userSuccess');

Route::get('/logout', 'UserController@logout');

Route::delete('/galleryDelete/{id}', 'PageController@galleryDelete');

Route::get('/resetPass', 'UserController@resetPass');

resources/views/partials/sidebars.blade.php
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="../../images/user.png" width="48" height="48" alt="User" />
            </div>
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administrador</div>
                <div class="email">admin@gmail.com</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i>
                            {{ __('Cerrar Sesion') }}
                        </a></li>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>      
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">
                    <a href="{{ route('home')}}">Inicio</a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">library_books</i>
                        <span>Revistas</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="{{ route('magazine.index')}}">Ver Revistas</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">subscriptions</i>
                        <span>Suscripciones</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="{{ route('subscription.index')}}">Ver Suscripciones</a>
                        </li>                
                    </ul>
                </li>
                <li>
                    <a href="/notices">
                        <i class="material-icons">textsms</i>
                        <span>Avisos</span>
                    </a>
                    
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">account_box</i>
                        <span>Usuarios</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="{{ route('user.index')}}">Ver Usuarios</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="/infopages/1/edit">
                        <i class="material-icons">person</i>
                        <span>Acerca de Nosotros</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; Develop by<a href="https://www.maadchile.cl" target="_blank">MaadChile 2020</a>.
            </div>
        </div>
        <!-- #Footer -->
    </aside>
</section>

resources/views/partials/topbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="../../index.html">FUEGO DE PENTECOSTES</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <div class="image text-right">
                <img src="../../images/logo.png"  alt="User"  style="width: 140px"/>
            </div>
        </div>
    </div>
</nav>