routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return redirect('/login');
});

Route::get('/', 'UserController@landing');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('infopages', 'InfoPagesController');

Route::resource('magazine', 'MagazineController');

Route::resource('notices', 'NoticeController');

Route::post('magazine/image', 'MagazineController@image')->name('magazine.image');

Route::resource('pages', 'PageController');

Route::get('/magazinePage/{id}','MagazineController@pages');

Route::resource('subscription', 'SubscriptionController');

Route::post('/contentImage', 'MagazineController@contentImage');

Route::post('/contentGallery/{id}', 'MagazineController@contentGallery');

Route::post('/pagePost', 'PageController@pagePost');

Route::get('/goFlow', 'SaleController@goFlow');

Route::post('/flowConfirm', 'SaleController@flowConfirm');

Route::post('/flowResult', 'SaleController@flowResult');

Route::get('/appRegister', 'UserController@appRegister');

Route::get('/paypalReturn', 'SaleController@paypalReturn');

Route::get('/paypalCancel', 'SaleController@paypalCancel');

Route::post('/registerApp', 'UserController@registerApp');

Route::get('/userSuccess', 'UserController@userSuccess');

Route::get('/logout', 'UserController@logout');

Route::delete('/galleryDelete/{id}', 'PageController@galleryDelete');

Route::get('/resetPass', 'UserController@resetPass');

app/User.php
<?php

namespace App;

use App\Subscription;
use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\MyResetPassword;


class User extends Authenticatable
{
    use Notifiable;
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type', 'subscription_id', 'fcm_token'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function subscription(){
        return $this->belongsTo(Subscription::class);
    }

    public function sales()
    {
        return $this->hasMany('App\Sale');
    }

    const TYPES = [
        1 => 'Admin',
        2 => 'Cliente',
        3 => 'Free Pass'
    ];

    const STATUS = array(
        1 => 'Pendiente',
        2 => 'Activo',
        3 => 'Cancelado',
        4 => 'Renovacion'
    );

    public function getTypelabelAttribute(){
        return Self::TYPES[$this->type];
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new MyResetPassword($token));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\{Subscription, Magazine, Page, Sale};
use Illuminate\Http\Request;
use App\Http\Requests\StoreUserPost;
use App\Http\Requests\UpdateUserPut;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Config;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Rest\ApiContext;
use PayPal\Api\{Payer, Payment, Amount, RedirectUrls, Transaction };
use Auth;

class UserController extends Controller
{
    public function appRegister() {
        $subs = Subscription::all();
        return view('auth.register', ['subs' => $subs]);
    }

    public function resetPass() {
        return view('resetPass');
    }

    public function landing() {
        $magazines = Magazine::where('status',1)->get();
       
        foreach ($magazines as $key => $m) {
            
            $pages = Page::where('magazine_id', $m->id)->orderBy('page')->get();

            $html = "<ul>";
            foreach ($pages as $key => $p) {
                $html .= "<li>".$p->page.".- ".$p->title."</li>";
            }
            $html .= "</ul>";

            $m->indexedpages = $html;
            
        }
        return view('welcome', ['magazines' => $magazines]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $selectTypes = User::TYPES;
        $users = User::orderBy('id','asc')->get();
        $subs = Subscription::get();
        return view('users.list', ['users' => $users, 'subs' => $subs, 'selectTypes' => $selectTypes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $selectTypes = User::TYPES;
        $subs = Subscription::get();
        return view('users.create', ['user'=> new User(), 'selectTypes' => $selectTypes, 'subs' => $subs]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserPost $request)
    {
        $subs = Subscription::get();
        
        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
            'type' => $request['type'],
            'subscription_id' => $request['subscription_id'],
        ]);

        return back()->with('status', 'Usuario Creado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $selectTypes = User::TYPES;
        $subs = Subscription::get();
        return view('users.edit', ['user' => $user, 'selectTypes' => $selectTypes, 'subs' => $subs]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserPut $request, User $user)
    {
        $user->update(
            [
            'name' => $request['name'],
            'email' => $request['email'],
            'type' => $request['type'],
            'subscription_id' => $request['subscription_id'],
            ]
        );

        return back()->with('status', 'Usuario Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return back()->with('status', 'Usuario Eliminado');
    }

    public function userSuccess() {
        return view('userSuccess');
    }

    public function logout() {
        Auth::logout();
        return redirect('/');
    }

    public function registerApp(Request $request) {
        
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'subscription_id' => 'required|integer',
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'subscription_id' => $request->subscription_id,
            'type' => 2,
        ]);

        $sub = Subscription::find($user->subscription_id);
        $total = $sub->price;
        if($total == 0) {
            if(count($user->sales) == 0) {
                $sale = new Sale;
                $sale->user_id = $user->id;
                $sale->subscription_id = $user->subscription_id;
                $sale->amount = $total;
                $sale->status = 1;
                $sale->save();

                return redirect('/userSuccess')->with('status', 'Suscripción Aprobada!');
        
            }else {
                return redirect('/userSuccess')->with('status', 'Tu Suscripción Gratuita ah pasado!');
            }
        }

        
        $sale = new Sale;
        $sale->user_id = $user->id;
        $sale->subscription_id = $user->subscription_id;
        $sale->amount = $total;
        $sale->status = 9;
        $sale->save();
        
        if($request->type == 1) {
            $optional = array(
                "id" => $sale->id,
            );
            $optional = json_encode($optional);

            $params = array(
                "commerceOrder" => 'FuegoPentecostes S000-'.$sale->id,
                "subject" => "Pago en Pentecostes",
                "currency" => "CLP",
                "amount" => $total,
                "email" => $user->email,
                "paymentMethod" => 9,
                "urlConfirmation" =>  "http://167.99.118.90/flowConfirm",
                "urlReturn" => "http://167.99.118.90/flowResult",
                "optional" => $optional
            );

            $serviceName = "payment/create";
            $flowApi = new FlowApi();
            $response = $flowApi->send($serviceName, $params,"POST");
            $redirect = $response["url"] . "?token=" . $response["token"];

            return redirect($redirect);
        }else if( $request->type == 2) {

            $paypalConfig = Config::get('paypal');
            
            $apiContext = new ApiContext(
                new OAuthTokenCredential(
                    $paypalConfig['client_id'],
                    $paypalConfig['secret']
                )
            );

            $payer = new Payer();
            $payer->setPaymentMethod('paypal');

            $amount = new Amount();
            $amount->setTotal($sub->dollar_price);
            $amount->setCurrency('USD');

            $transaction = new Transaction();
            $transaction->setAmount($amount);
            $transaction->setDescription($sub->name);
            $transaction->setInvoiceNumber($sale->id);

            $returnUrl = url("/paypalReturn");
            $paypalUrl = url("/paypalCancel");

            $redirectUrls = new RedirectUrls();
            $redirectUrls->setReturnUrl($returnUrl)
                ->setCancelUrl($paypalUrl);

            $payment = new Payment();
            $payment->setIntent('sale')
                ->setPayer($payer)
                ->setTransactions(array($transaction))
                ->setRedirectUrls($redirectUrls);

            try {
                $payment->create($apiContext);
                return redirect()->away($payment->getApprovalLink());
            }
            catch (\PayPal\Exception\PayPalConnectionException $ex) {
                echo $ex->getData();
            }


        }

        
    }
}

app/Http/Controllers/api/UserController.php
<?php

namespace App\Http\Controllers\api;

use App\User;
use App\Subscription;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends ApiResponseController
{

    public function index()
    {
        $users = User::
        join('subscriptions', 'subscriptions.id', '=', 'users.subscription_id')->
        select('users.*', 'subscriptions.name as subscription')->get();
        return $this->successResponse($users);
    }

    public function show(User $user)
    {   
        $user->subscription;
        return $this->successResponse($user);
    }

    public function subscription(Subscription $subscription)
    {   
        return $this->successResponse(["users" => $subscription->user, "subscription" => $subscription]);
    }


}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

@if ($errors->any())
@foreach ($errors->all() as $error)
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{$error}}
    </div> 
@endforeach

@endif

    <form action="{{ route('user.store')}}" method="POST">

        @csrf
        <input type="hidden" id="token" value="{{csrf_token()}}">
        <input type="hidden" name="subscription_id" value="0">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        
        <div class="row clearfix">
            <div class=" col-md-offset-1 col-lg-offset-1 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Crea Usuario
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="">Nombre</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">person</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Nombre">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Email</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">email</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="email" name="email" id="email" class="form-control" placeholder="Email">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Tipo Usuario</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">supervisor_account</i>
                                    </span>
                                    <select class="form-control" name="type" id="type"  placeholder="type">
                                        <option>Tipo Usuario</option>
                                        @foreach ($selectTypes as $key => $value)
                                            <option value="{{$key}}">{{$value}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>        
                            <div class="col-md-6">
                                <label for="">Tipo Suscripcion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">shop_two</i>
                                    </span>
                                    <select class="form-control" id="subscription_id"  placeholder="">
                                        <option>Tipo Suscripcion</option>
                                        @foreach ($subs as $s)
                                            <option value="{{$s->id}}">{{$s->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Contraseña</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">vpn_key</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="password" name="password" id="password" class="form-control" placeholder="Contraseña">
                                    </div>
                                </div>
                            </div>
                            <div class=" row col-md-12 text-right">
                                <input type="submit" value="Crear" class="btn btn-danger" style="width:200px">
                            </div>                          
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection
@section('scripts')

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

@if ($errors->any())
@foreach ($errors->all() as $error)
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{$error}}
    </div> 
@endforeach

@endif
    <form action="{{ route('user.update', $user->id)}}" method="POST">

        @method('PUT')

        @csrf
        <input type="hidden" id="token" value="{{csrf_token()}}">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <div class="row clearfix">
            <div class=" col-md-offset-1 col-lg-offset-1 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Editar Usuario
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="">Nombre</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">person</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" value="{{$user->name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Email</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">email</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="email" name="email" id="email" class="form-control" value="{{$user->email}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Tipo Usuario</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">supervisor_account</i>
                                    </span>
                                    <select class="form-control" name="type" id="type"  placeholder="type">
                                        <option>Tipo Usuario</option>
                                        @foreach ($selectTypes as $key => $value)
                                            <option {{ $user->type == $key ? 'selected':'' }} value="{{$key}}">{{$value}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>  
                            <div class="col-md-6">
                                <label for="">Tipo Suscripcion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">shop_two</i>
                                    </span>
                                    <select class="form-control" name="subscription_id" id="subscription_id" placeholder="">
                                        <option>Tipo Suscripcion</option>
                                        @foreach ($subs as $s)
                                            <option {{ $user->subscription_id == $s->id ? 'selected':'' }} value="{{$s->id}}">{{$s->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class=" row col-md-12 text-right">
                                <input type="submit" value="Actualizar" class="btn btn-danger" style="width:200px">
                            </div>   
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/users/list.blade.php
@extends('layouts.app')

@section('css')
     <!-- JQuery DataTable Css -->
     <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@endsection

@section('content')


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Usuarios
                    <form action="{{ route('user.create')}}" method="GET" class="pull-right">
                        <button type="sumbit" class="btn btn-primary">Crear Usuario</button>
                    </form>
                </h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            <tr>                            
                                <th>Nombre</th>
                                <th>Email</th>
                                <th>Tipo</th>
                                <th>Tipo de Suscripcion</th>
                                <th>Acciones</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($users as $u)
                            <tr>
                                <td>{{$u->name}}</td>
                                <td>{{$u->email}}</td>
                                <th>{{$u->typelabel}}</th>
                                <th>{{$u->subscription->name ?? ''}}</th>
                                <th>
                                    <a href=" {{ route('user.edit', $u->id) }} " class="btn btn-primary"> Actualizar </a>
                                    <button data-toggle="modal" data-target="#deleteModal" data-id="{{$u->id}}" class="btn btn-danger"> Eliminar </button>
                                </th>
                            </tr>
                        @endforeach    
                        </tbody>
                    </table>
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="smallModalLabel">Seguro?</h4>
                                </div>
                                <div class="modal-body">
                                    Seguro?
                                </div>
                                <div class="modal-footer">
                                    <form id="formDelete" method="POST" action="{{ route('user.destroy', 0)}}" data-action="{{ route('user.destroy', 0)}}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="sumbit" class="btn btn-link waves-effect">Borrar</button>
                                    </form>
                                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
      <!-- Jquery DataTable Plugin Js -->
      <script src="/plugins/jquery-datatable/jquery.dataTables.js"></script>
      <script src="/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
  
      <!-- Custom Js -->

      <script src="/js/pages/tables/jquery-datatable.js"></script>
    <script>
        window.onload = function(){
            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var id = button.data('id') 
    
                action = $('#formDelete').attr('data-action').slice(0,-1) 
                $('#formDelete').attr('action',action + id)
    
                var modal = $(this)
                modal.find('.modal-title').text('Vas a borrar el usuario: ' + id)
                });
        };
    </script>
@endsection