routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return redirect('/login');
});

Route::get('/', 'UserController@landing');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('infopages', 'InfoPagesController');

Route::resource('magazine', 'MagazineController');

Route::resource('notices', 'NoticeController');

Route::post('magazine/image', 'MagazineController@image')->name('magazine.image');

Route::resource('pages', 'PageController');

Route::get('/magazinePage/{id}','MagazineController@pages');

Route::resource('subscription', 'SubscriptionController');

Route::post('/contentImage', 'MagazineController@contentImage');

Route::post('/contentGallery/{id}', 'MagazineController@contentGallery');

Route::post('/pagePost', 'PageController@pagePost');

Route::get('/goFlow', 'SaleController@goFlow');

Route::post('/flowConfirm', 'SaleController@flowConfirm');

Route::post('/flowResult', 'SaleController@flowResult');

Route::get('/appRegister', 'UserController@appRegister');

Route::get('/paypalReturn', 'SaleController@paypalReturn');

Route::get('/paypalCancel', 'SaleController@paypalCancel');

Route::post('/registerApp', 'UserController@registerApp');

Route::get('/userSuccess', 'UserController@userSuccess');

Route::get('/logout', 'UserController@logout');

Route::delete('/galleryDelete/{id}', 'PageController@galleryDelete');

Route::get('/resetPass', 'UserController@resetPass');

app/Magazine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Magazine extends Model
{
    protected $fillable = [
        'name', 'img', 'description', 'edit_date', 'created_by','status', 'background_image'
    ];

    public function pages()
    {
        return $this->hasMany('App\Page');
    }
    const STATUS = [
        1 => 'Publicada',
        2 => 'No Publicada'
    ];
    public function getStatuslabelAttribute(){
        return Self::STATUS[$this->status];
    }

    public function user() {
        return $this->belongsTo('\App\User','created_by');
    }

    public function indexpages() {
        
        function order($object1, $object2) { 
            return $object1->page > $object2->page; 
        } 

        $pages = $this->hasMany('App\Page');
        usort($pages->toArray(), 'order');
        $html = "<ul>";
        foreach ($pages as $key => $p) {
            $html .= "<li>".$p->page.".- ".$p->title."</li>";
        }
        $html .= "</ul>";

        return $html;
    }
}

app/Http/Controllers/MagazineController.php
<?php

namespace App\Http\Controllers;

use URL;
use App\Page;
use App\Magazine;
use App\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreMagazinePost;

class MagazineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = Page::get();
        $user = Auth::user();     
        $magazines = Magazine::orderBy('edit_date','desc')->get();

        return view('magazines.list', ['magazines' => $magazines, 'user' => $user, 'pages' => $pages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $selectStatus = Magazine::STATUS;
        $user = Auth::user();
        return view('magazines.create', ['magazine'=> new Magazine(), 'user' => $user, 'selectStatus' => $selectStatus]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMagazinePost $request)
    {
        $magazine = Magazine::create($request->all());

        if ($request->file('img')) {
			$path = $request->file('img')->store('public');
			$img  = str_replace('public/', '', $path);
			$magazine->img = $img;
			$magazine->save();
        }
        
        if ($request->file('background_image')) {
            $path = $request->file('background_image')->store('public');
            $img  = str_replace('public/', '', $path);
            $magazine->background_image = $img;
            $magazine->save();
        }

        return back()->with('status', 'Revista Creada');
			
    }      

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Magazine $magazine)
    {
        $selectStatus = Magazine::STATUS;
        $user = Auth::user();
        return view('magazines.edit', ['magazine' => $magazine, 'user' => $user, 'selectStatus' => $selectStatus]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Magazine $magazine)
    {
        $magazine->update($request->all());

        if ($request->file('img')) {
			$path = $request->file('img')->store('public');
			$img  = str_replace('public/', '', $path);
			$magazine->img = $img;
			$magazine->save();
        }
        
        if ($request->file('background_image')) {
            $path = $request->file('background_image')->store('public');
            $img  = str_replace('public/', '', $path);
            $magazine->background_image = $img;
            $magazine->save();
        }

        return back()->with('status', 'Revista Actualizada');
			
    } 

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Magazine $magazine)
    {
        $magazine->delete();

        return back()->with('status', 'Revista Eliminada');
    }

    public function contentImage(Request $request) {

        $filename = time() . "." . $request->fileToUpload->extension();

        $request->fileToUpload->move(public_path('images_ckeditor'), $filename);

        return response()->json(['success'=>true,'file'=> URL::to('/') . '/images_ckeditor'.'/'. $filename]);
    }

    public function contentGallery(Request $request, $id) {
        
        $filename = time() . "." . $request->file->extension();

        $request->file->move(public_path('images_gallery'), $filename);
        
        $gallery = new Gallery([
            'path' => $filename,
            'page_id'=> $id
        ]);

        $gallery->save();

        return response()->json(['success'=>true,'file'=> URL::to('/') . '/images_gallery'.'/'. $filename]);
    }

    public function pages($id)
    {     
        $magazine = Magazine::findOrFail($id);
        $pages = Page::where('magazine_id',$magazine->id)->orderBy('id','asc')->get();
        $selectTypes = Page::TYPES;  
        return view('mPages.list', ['magazine' => $magazine,'pages' => $pages, 'selectTypes' => $selectTypes]);
    }

}

app/Http/Controllers/api/MagazineController.php
<?php

namespace App\Http\Controllers\api;

use App\{Magazine, Page};
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Carbon\Carbon;

class MagazineController extends ApiResponseController
{
    public function orderCall($object1, $object2) { 
        return $object1['page'] > $object2['page']; 
    } 

    public function index()
    {
        $user = Auth::user();
        
        if ($user->type === 2) {
            $cDate = new Carbon($user->created_at);
            $sale = $user->sales->last();
            $months = $sale->subscription->months;
            $dDate = new Carbon($user->created_at);
            $to = $dDate->addMonths($months);
            $magazines = Magazine::where('edit_date', '>=', $cDate->firstOfMonth())->where('edit_date','<=',$to )->where('status',1)->get();
        } else {
            $magazines = Magazine::where('status',1)->get();
        }
        
       
        foreach ($magazines as $key => $m) {
            
            $pages = Page::where('magazine_id', $m->id)->orderBy('page')->get();

            $html = "<ul>";
            foreach ($pages as $key => $p) {
                $html .= "<li>".$p->page.".- ".$p->title."</li>";
            }
            $html .= "</ul>";

            $m->indexedpages = $html;
            
        }
        
        return $this->successResponse($magazines);
    }

    public function show(Magazine $magazine)
    {   
        return $this->successResponse($magazine);
    }

    public function magazinePages($id) {
        $pages = Page::with('galleries')->where('magazine_id', $id)->orderBy('page')->get();
        foreach ($pages as $key => $p) {
            foreach ($p->galleries as $k => $g) {
                $p->galleries[$k] = $g->path;
            }
        }
        return $this->successResponse($pages);
    }

}

resources/views/magazines/create.blade.php
@extends('layouts.app')

@section('content')

@section('css')
    <link href="/plugins/dropzone/dropzone.css" rel="stylesheet">
    <link rel="stylesheet" href="/trumbowyg/dist/ui/trumbowyg.min.css">
    <link rel="stylesheet" href="/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.min.css">
@endsection

@if ($errors->any())
@foreach ($errors->all() as $error)
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{$error}}
    </div> 
@endforeach

@endif

    <form action="{{ route('magazine.store')}}" method="POST" enctype="multipart/form-data">

        @csrf
        <input type="hidden" name="created_by" value="{{$user->id}}">
        <input type="hidden" id="token" value="{{csrf_token()}}">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        
        <div class="row clearfix">
            <div class=" col-md-offset-1 col-lg-offset-1 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Crear Revista
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row ">
                            <div class="col-md-6">
                                <label for="">Portada</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">title</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="file" name="img" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Fondo Horizontal</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">insert_photo</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="file" name="background_image" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Titulo</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">title</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Titulo">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Estado</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">check_circle</i>
                                    </span>
                                    <select class="form-control" name="status" id="status"  placeholder="status">
                                        @foreach ($selectStatus as $key =>$value)
                                            <option value="{{$key}}">{{$value}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6" style="clear:both">
                                <label for="">Fecha de Publicacion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">date_range</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="date" name="edit_date" id="edit_date" class="form-control" placeholder="Fecha Edicion">
                                    </div>
                                </div>
                            </div>    
                            <div class="col-md-12">
                                <label for="">Descripcion</label>
                                <textarea name="description" id="trumbowyg-demo" class="form-control"></textarea>
                            </div>
                            <div class=" row col-md-12 text-right">
                                <input type="submit" value="Crear" class="btn btn-danger" style="width:200px">
                            </div>
                        </div>       
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script src="/trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="/trumbowyg/dist/plugins/lineheight/trumbowyg.lineheight.min.js"></script>
    <script src="/trumbowyg/dist/plugins/fontfamily/trumbowyg.fontfamily.min.js"></script>
    <script src="/trumbowyg/dist/plugins/fontsize/trumbowyg.fontsize.min.js"></script>
    <script src="/trumbowyg/dist/plugins/upload/trumbowyg.upload.min.js"></script>
    <script src="/trumbowyg/dist/plugins/insertaudio/trumbowyg.insertaudio.min.js"></script>
    <script src="/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js"></script>
    <script type="/text/javascript" src="/trumbowyg/dist/langs/es.min.js"></script>
    <script src="/trumbowyg/dist/plugins/noembed/trumbowyg.noembed.min.js"></script>

        <script>
            $(function(){
                $('#trumbowyg-demo').trumbowyg({
                    lang: 'es',
                    btns: [
                        
                        ['fontfamily','formatting','strong', 'em', 'del'],
                        ['foreColor', 'backColor'],
                        ['link'],
                        ['insertImage','upload','insertAudio', 'noembed'],
                        ['unorderedList', 'orderedList'],
                        ['viewHTML'],
                        ['undo', 'redo'], // Only supported in Blink browsers
                                         ['horizontalRule'],
                        ['lineheight','justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                        ['fullscreen'],
                    ],
                    plugins: {
                        upload: {
                            serverPath:"http://fuegodepentecostes.cl/contentImage"
                        }
                    }
                });
            })
        </script>
@endsection

resources/views/magazines/edit.blade.php
@extends('layouts.app')

@section('css')
    <link href="/plugins/dropzone/dropzone.css" rel="stylesheet">
    <link rel="stylesheet" href="/trumbowyg/dist/ui/trumbowyg.min.css">
    <link rel="stylesheet" href="/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.min.css">
@endsection

@section('content')


    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{$error}}
            </div> 
        @endforeach
    @endif

    <form action="{{ route('magazine.update', $magazine->id)}}" method="POST" enctype="multipart/form-data">
        @method('PUT')

        @csrf

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <input type="hidden" name="created_by" value="{{$magazine->created_by}}">
        <input type="hidden" id="token" value="{{csrf_token()}}">
        
        <div class="row clearfix">
            <div class="col-md-offset-1 col-lg-offset-1 col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Editar Revista
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row clearfix">
                            <div class="col-md-6">
                                <label for="">Portada</label>
                                <img src="/storage/{{$magazine->img}}" alt="" style="max-width: 200px">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">title</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="file" name="img" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Fondo Horizontal</label>
                                <img src="/storage/{{$magazine->background_image}}" alt="" style="max-width: 200px">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">insert_photo</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="file" name="background_image" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Titulo</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">title</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" value="{{$magazine->name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="">Estado</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">check_circle</i>
                                    </span>
                                    <select class="form-control" name="status" id="status"  placeholder="status">
                                        <option>Estado</option>
                                        @foreach ($selectStatus as $key =>$value)
                                            <option {{ $magazine->status == $key ? 'selected':'' }} value="{{$key}}">{{$value}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6" style="clear:both">
                                <label for="">Fecha de Publicacion</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">date_range</i>
                                    </span>
                                    <div class="form-line">
                                        <input type="date" name="edit_date" id="edit_date" class="form-control" value="{{$magazine->edit_date}}">
                                    </div>
                                </div>
                            </div>    
                            <div class="col-md-12">
                                <label for="">Descripcion</label>
                            <textarea name="description" id="trumbowyg-demo" class="form-control">{{$magazine->description}}</textarea>
                            </div>     
                            <div class=" row col-md-12 text-right">
                                <input type="submit" value="Actualizar" class="btn btn-danger" style="width:200px">
                            </div>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script src="/trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="/trumbowyg/dist/plugins/lineheight/trumbowyg.lineheight.min.js"></script>
    <script src="/trumbowyg/dist/plugins/fontfamily/trumbowyg.fontfamily.min.js"></script>
    <script src="/trumbowyg/dist/plugins/fontsize/trumbowyg.fontsize.min.js"></script>
    <script src="/trumbowyg/dist/plugins/upload/trumbowyg.upload.min.js"></script>
    <script src="/trumbowyg/dist/plugins/insertaudio/trumbowyg.insertaudio.min.js"></script>
    <script src="/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js"></script>
    <script type="/text/javascript" src="/trumbowyg/dist/langs/es.min.js"></script>
    <script src="/trumbowyg/dist/plugins/noembed/trumbowyg.noembed.min.js"></script>
        <script>
            $(function(){
                $('#trumbowyg-demo').trumbowyg({
                    lang: 'es',
                    btns: [
                        
                        ['fontfamily','formatting','strong', 'em', 'del'],
                        ['foreColor', 'backColor'],
                        ['link'],
                        ['insertImage','upload','insertAudio', 'noembed'],
                        ['unorderedList', 'orderedList'],
                        ['viewHTML'],
                        ['undo', 'redo'], // Only supported in Blink browsers
                       
                        ['horizontalRule'],
                        ['lineheight','justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                        ['fullscreen'],
                    ],
                    plugins: {
                        upload: {
                            serverPath:"http://fuegodepentecostes.cl/contentImage"
                        }
                    }
                });
            })
        </script>
@endsection

resources/views/magazines/list.blade.php
@extends('layouts.app')

@section('css')
     <!-- JQuery DataTable Css -->
     <link href="../../plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@endsection

@section('content')

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Revistas
                    <form action="{{ route('magazine.create')}}" method="GET" class="pull-right">
                        <button type="sumbit" class="btn btn-primary">Crear Revista</button>
                    </form>
                </h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            <tr>
                                <th>Titulo</th>
                                <th>Imagen</th>
                                <th>Imagen Fondo</th>
                                <th>Descripcion</th>
                                <th>Fecha de Edicion</th>
                                <th>Creada por</th>
                                <th>Status</th>
                                <th>Acciones</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($magazines as $m)
                            <tr>
                                <td>{{$m->name}}</td>
                                <td><img src="{{asset('storage/'.$m->img)}}" width="150" /></td>
                                <td><img src="{{asset('storage/'.$m->background_image)}}" width="150" /></td>
                                <th>{!!$m->description!!}</th>
                                <th>{{$m->edit_date}}</th>
                                <th>{{$m->user->f}}</th>
                                <th>{{$m->statuslabel}}</th>
                                <th>
                                    <a href=" {{ route('magazine.edit', $m->id) }} " class="btn btn-primary"> Actualizar </a>
                                    <button data-toggle="modal" data-target="#deleteModal" data-id="{{$m->id}}" class="btn btn-danger"> Eliminar </button>
                                <a href="/magazinePage/{{$m->id}}" class="btn btn-success"> Paginas </a>
                                </th>
                            </tr>
                        @endforeach    
                        </tbody>
                    </table>
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="smallModalLabel">Seguro?</h4>
                                </div>
                                <div class="modal-body">
                                    Seguro?
                                </div>
                                <div class="modal-footer">
                                    <form id="formDelete" method="POST" action="{{ route('magazine.destroy', 0)}}" data-action="{{ route('magazine.destroy', 0)}}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="sumbit" class="btn btn-link waves-effect">Borrar</button>
                                    </form>
                                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
      <!-- Jquery DataTable Plugin Js -->
      <script src="/plugins/jquery-datatable/jquery.dataTables.js"></script>
      <script src="/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
      <script src="/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
  
      <!-- Custom Js -->

      <script src="/js/pages/tables/jquery-datatable.js"></script>
      
    <script>
        window.onload = function(){
            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var id = button.data('id') 
    
                action = $('#formDelete').attr('data-action').slice(0,-1) 
                $('#formDelete').attr('action',action + id)
    
                var modal = $(this)
                modal.find('.modal-title').text('Vas a borrar esta revista ' + id)
                });
        };
    </script>
@endsection